#!/usr/bin/zsh

# update dnf
echo "Updating dnf packages..."
sudo dnf -y update

# upgrade dnf
echo "Upgrading dnf packages..."
sudo dnf -y upgrade

# clean up dnf
echo "Cleaning up unused dnf dependencies..."
sudo dnf -y autoremove

# clear dnf cache
echo "Clearing dnf cache..."
sudo dnf -y clean all

# update om-my-zsh
echo "Updating oh-my-zsh..."
ZSH='/home/neal/.oh-my-zsh'
zsh "$ZSH/tools/upgrade.sh"

# initialize zinit for this shell
source "/home/neal/.local/share/zinit/zinit.git/zinit.zsh"

# update zinit
echo "Updating zinit..."
zi self-update

# update zinit plugins
echo "Updating zinit plugins..."
zi update --parallel

# update neovim plugins via lazy.nvim
nvim --headless "+Lazy! sync" +qa
