#!/bin/bash

if [ "$1" = "--speak" ]; then
  doSpeak=true
else
  doSpeak=
fi

speak() {
    if [ $doSpeak ]; then
      say $1
    fi
}

# update homebrew
echo Updating...
speak "Updating"
brew update

# upgrade packages
echo Upgrading non-casks...
speak "Upgrading see el eye tools"
brew upgrade

# upgrade casks
echo Upgrading casks...
speak "Upgrading casks"
brew cask upgrade

# remove old package versions
echo Removing old versions...
speak "Removing old versions"
brew cleanup

# confirm system integrity
echo Running brew system check...
speak "Running brew doctor"
brew doctor
